### ISSUE TITLE
Webロゴ掲載（株式会社ビズリーチ様）

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2022.scalamatsuri.org#46]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template:
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “https://www.visional.inc/ja/careers.html”
}
ロゴ画像:https://drive.google.com/file/d/18XvMSJRtM0XFJOD0kGXa0AVTtLhu3xZW/view?usp=sharing

**Comment by Iwaji** [comment]
ご参考：備考欄の記載内容
> 前回同様ロゴ等の露出は「Visional」（※グループ名）、申込みや支払い等の事務手続きは株式会社ビズリーチ宛でお願いしたいです。

**Comment by tomoco95** [comment]
掲載と、掲載完了のご連絡をしました
