### ISSUE TITLE
Webロゴ掲載(FLINTERS様)

### ISSUE THREAD

**Issue by tomoco95** [scalamatsuri/2022.scalamatsuri.org#59]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 "name": "",
 "logo": "",
 "url": "https://www.flinters.co.jp/"
}

ロゴ画像:https://drive.google.com/file/d/1WQSWz8LYlu3Eb4AN8V1qozpixGI2nKxr/view?usp=sharing

**Comment by tomoco95** [comment]
遷移先のURL確認中です

**Comment by Iwaji** [comment]
URL確認できました！
（Issueが編集できなかったので、コメントとして記載しました。）
https://www.flinters.co.jp/

**Comment by tomoco95** [comment]
掲載と、掲載完了のご連絡をしました
