### ISSUE TITLE
Webロゴ掲載（日本インサイトテクノロジー様）

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2022.scalamatsuri.org#66]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “http://www.insightech.co.jp/”
}
ロゴ画像:https://drive.google.com/file/d/1YLPYHqviuOuGOedE3-6jCN2hWdL_4Zxj/view?usp=sharing

**Comment by tomoco95** [comment]
掲載と、掲載完了のご連絡をしました
