### ISSUE TITLE
Webロゴ掲載（株式会社ギブリー様）

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2022.scalamatsuri.org#90]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “https://tracks.run/”
}
ロゴ画像:https://drive.google.com/file/d/1usWdNA1hXWZIgIddIF_2LUCqotSLknFw/view?usp=sharing

**Comment by tomoco95** [comment]
掲載・掲載完了のご連絡をしました
