### ISSUE TITLE
Webロゴ掲載（株式会社ネクストビート様）

### ISSUE THREAD

**Issue by Iwaji** [scalamatsuri/2022.scalamatsuri.org#91]
- [x] リポジトリにロゴを入れる
- [x] jsonファイルを変更する
- [x] develop branchに向けてPullRequestを送る
- [x] staging環境で表示を確認する
- [x] developからmaster branchに向けてPullRequestを送る
- [x] merge後、production環境のWebサイトに反映されていることを確認する

template: 
```
,{
 “name”: “”,
 “logo”: “”,
 “url”: “https://www.nextbeat.co.jp/”
}
ロゴ画像：https://drive.google.com/file/d/1S43v2dOny7xgrMi_iil_xxJgCpjThsnk/view?usp=sharing

**Comment by tomoco95** [comment]
掲載、掲載完了のご連絡をしました
